[book]
title = "Discovery"
description = "Discover the world of microcontrollers through Rust"
authors = ["Rust Embedded Resources Team"]
language = "en"

[output.html]
additional-css = ["custom.css"]
git-repository-url = "https://github.com/rust-embedded/discovery/"
